---
- name: Create application directory
  file:
    path: /opt/project3
    state: directory
    owner: sergeymazov
    group: docker
    mode: '0755'

- name: Create data directory for images
  file:
    path: /opt/project3/images
    state: directory
    owner: sergeymazov
    group: docker
    mode: '0777'

- name: Login to GitHub Container Registry
  docker_login:
    registry_url: ghcr.io
    username: "{{ ghcr_username }}"
    password: "{{ ghcr_password }}"

- name: Pull specific version Docker image
  docker_image:
    name: "ghcr.io/otfantik/project-devops-deploy:{{ docker_image_version }}"
    source: pull

- name: Stop and remove old container if exists
  docker_container:
    name: project3-app
    state: absent

- name: Run new container
  docker_container:
    name: project3-app
    image: "ghcr.io/otfantik/project-devops-deploy:{{ docker_image_version }}"
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - /opt/project3/images:/tmp/bulletin-images
    env:
      SPRING_PROFILES_ACTIVE: "{{ spring_profiles_active | default('dev') }}"